// src/angular/root.component.ts
import { Component } from '@angular/core';
import '../../assets/styles/public.css';

@Component({
  selector: 'angularApp',
  template: `
    <nav class="app-nav">
      <ul class="nav-list">
        <li>
          <a [routerLink]="['']" routerLinkActive="active">Home</a>
        </li>
        <li>
          <a [routerLink]="['/about']" routerLinkActive="active">About</a>
        </li>
        <li>
          <a [routerLink]="['/todoList']" routerLinkActive="active">Todo List</a>
        </li>
      </ul>
    </nav>
    <div class="app-box">
      <h1>
        Current is Angular-app.
      </h1>
      <router-outlet></router-outlet> 
    </div>
  `,
})
export default class AppComponent {
}

// vue/src/root.component.vue
<template>
  <div>
    <nav class="app-nav">
      <ul class="nav-list">
        <li>
          <router-link to="/">Home</router-link>
        </li>
        <li>
          <router-link to="/about">About</router-link>
        </li>
        <li>
          <router-link to="/todoList">Todo List</router-link>
        </li>
      </ul>
    </nav>
    <div class="app-box">
      <h1>Current is Vue-app.</h1>
      <router-view></router-view>
    </div>
  </div>
</template>

<script>
export default {
name:'app',
 data(){
   return {
       
    }
 },
}
</script>

<style>
@import './styles/app-nav.css';
</style>
