// src/angular/app.js
import 'zone.js';
import 'reflect-metadata';
import singleSpaAngular from 'single-spa-angular';
import { ApplicationRef } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import mainModule from './main-module.ts';
import { Router } from '@angular/router';

const ngLifecycles = singleSpaAngular({
  domElementGetter:()=>document.getElementById('angular-app'),
  mainModule,
  angularPlatform: platformBrowserDynamic(),
  template: `<angularApp />`,
  Router,
  ApplicationRef,
})

export function bootstrap(props) {
  console.log('angular-app is bootstrap')
  return ngLifecycles.bootstrap(props);
}

export function mount(props) {
  console.log('angular-app is Mounted')
  return ngLifecycles.mount(props).then(val => {});
}

export function unmount(props) {
  console.log('angular-app is unMounted')
  return ngLifecycles.unmount(props);
}

// src/react/app.js
import React from 'react';
import ReactDOM from 'react-dom';
import singleSpaReact from 'single-spa-react';
import Root from './root.component.js';

const reactLifecycles = singleSpaReact({
  React,
  ReactDOM,
  rootComponent: Root,
  domElementGetter: () => document.getElementById('react-app')
});

export function bootstrap(props) {
  console.log('react-app is bootstrap')
  return reactLifecycles.bootstrap(props);
}

export function mount(props) {
  console.log('react-app is Mounted')
  return reactLifecycles.mount(props);
}

export function unmount(props) {
  console.log('react-app is unMounted')
  return reactLifecycles.unmount(props);
}
